output-format: text

strictness: veryhigh
doc-warnings: false
test-warnings: true
member-warnings: true

uses:
  - django

ignore-paths:
  - venv
  - env
  - .env
  - .venv

pep8:
  full: true
  options:
    max-line-length: 100
  disable:
    - N805

pylint:
  options:
    max-line-length: 100
  disable:
    - no-self-use
    - no-self-argument
    - unsubscriptable-object
    - too-few-public-methods

dodgy:
  run: true

ignore-patterns:
  - .+/migrations/.+
  - .+/settings/.+
